/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as UserIndexImport } from './routes/user/index'
import { Route as PaymentIndexImport } from './routes/payment/index'
import { Route as PaymentStatusImport } from './routes/payment/status'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UserIndexRoute = UserIndexImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => rootRoute,
} as any)

const PaymentIndexRoute = PaymentIndexImport.update({
  id: '/payment/',
  path: '/payment/',
  getParentRoute: () => rootRoute,
} as any)

const PaymentStatusRoute = PaymentStatusImport.update({
  id: '/payment/status',
  path: '/payment/status',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/payment/status': {
      id: '/payment/status'
      path: '/payment/status'
      fullPath: '/payment/status'
      preLoaderRoute: typeof PaymentStatusImport
      parentRoute: typeof rootRoute
    }
    '/payment/': {
      id: '/payment/'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentIndexImport
      parentRoute: typeof rootRoute
    }
    '/user/': {
      id: '/user/'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/payment/status': typeof PaymentStatusRoute
  '/payment': typeof PaymentIndexRoute
  '/user': typeof UserIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/payment/status': typeof PaymentStatusRoute
  '/payment': typeof PaymentIndexRoute
  '/user': typeof UserIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/payment/status': typeof PaymentStatusRoute
  '/payment/': typeof PaymentIndexRoute
  '/user/': typeof UserIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/payment/status' | '/payment' | '/user'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/payment/status' | '/payment' | '/user'
  id: '__root__' | '/' | '/payment/status' | '/payment/' | '/user/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PaymentStatusRoute: typeof PaymentStatusRoute
  PaymentIndexRoute: typeof PaymentIndexRoute
  UserIndexRoute: typeof UserIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PaymentStatusRoute: PaymentStatusRoute,
  PaymentIndexRoute: PaymentIndexRoute,
  UserIndexRoute: UserIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/payment/status",
        "/payment/",
        "/user/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/payment/status": {
      "filePath": "payment/status.tsx"
    },
    "/payment/": {
      "filePath": "payment/index.tsx"
    },
    "/user/": {
      "filePath": "user/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
